from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
import time,pyautogui
from selenium.webdriver.chrome.options import Options
chrome_options = Options()
chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
driver = webdriver.Chrome(options=chrome_options)
#driver.switch_to.window(driver.window_handles[0])
#driver.get("https://shop.nijisanji.jp/s/niji/item/detail/SSZS-27286?ima=0842")
buy1 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li[1]/div[2]/div[2]/div/button')))
buy1.click()
buy2 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li[2]/div[2]/div[2]/div/button')))
buy2.click()
for i in range (4):
    pyautogui.hotkey('ctrl', 't', interval=0.0001)
driver.switch_to.window(driver.window_handles[1])
driver.get("https://shop.nijisanji.jp/s/niji/item/detail/SSZS-31008?ima=5023")
buy1 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li/div[2]/div[2]/div/button')))
buy1.click()
driver.switch_to.window(driver.window_handles[2])
driver.get("https://shop.nijisanji.jp/s/niji/item/detail/SSZS-27578?ima=5023")
buy1 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li/div[2]/div[2]/div/button')))
buy1.click()
driver.switch_to.window(driver.window_handles[3])
driver.get("https://shop.nijisanji.jp/s/niji/item/detail/SSZS-27579?ima=5023")
buy1 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li[2]/div[2]/div[2]/div/button')))
buy1.click()
buy2 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li[3]/div[2]/div[2]/div/button')))
buy2.click()
buy3 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li[6]/div[2]/div[2]/div/button')))
buy3.click()
driver.switch_to.window(driver.window_handles[4])
driver.get("https://shop.nijisanji.jp/s/niji/item/detail/SSZS-27585?ima=5023")
buy1 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li[2]/div[2]/div[2]/div/button')))
buy1.click()
buy2 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li[3]/div[2]/div[2]/div/button')))
buy2.click()
buy3 = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/main/div/div/div/div[2]/div/div[5]/ul/li[6]/div[2]/div[2]/div/button')))
buy3.click()
time.sleep(1)
StoreCar = WebDriverWait(driver, 1000).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="VUE_APP_ROOT"]/div/div/header/div[1]/div/nav/div[1]/form[2]/button')))
StoreCar.click()
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[1]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[2]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[3]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[4]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[5]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[6]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[7]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[8]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[9]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
item = driver.find_element(By.XPATH,'//*[@id="app"]/div[1]/main/div/div[1]/div[2]/form/div[10]/div[1]/div[4]/div/input')
item.clear()
item.send_keys("5")
time.sleep(2)
driver.execute_script("window.scrollBy(0, document.body.scrollHeight);")
pyautogui.moveTo(1080,809, duration = 0.1)
pyautogui.click() 